# -*- coding: utf-8 -*-
"""PythoneAssignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ItMfTzMPd1514iakphu1v0C9_RBbHC15
"""

print("Hellow World!") ## Write a Python program to print "Hello, World!_

##Write a Python program that displays your name and age
Name = input("my name is ")
Age = input("my age is ")
##print("Name-",Name,"Age-",Age)

import keyword ##Write code to print all the pre-defined keywords in Python using the keyword library
print(keyword.kwlist)

##Write a program that checks if a given word is a Python keyword
#import keyword
#keycheck = input()
#for i in keycheck:
  #for kw in keyword.kwlist:
    #if kw == i:
      #print("this is keyword")
keycheck = input("Enter a word: ")
if keycheck in keyword.kwlist:
  print("oh this is a keyword")
else:
  print("this is not a keyword")

##Create a list and tuple in Python, and demonstrate how attempting to change an element works differently
L1 = ["Ram","Shyam","24"]
print(L1)
L1[1] = 25
print(L1)
Tup = ("Vivek", "shyam", "ddfd")
print(Tup)
##Tup[2] = 14, we can not assign any new value
print(Tup[2])

##0 Write a function to demonstrate the behavior of mutable and immutable arguments0
L2 = [12,23,34,34]
L3 = ["viren","goyal","govind"]
L4 = L2[1] = 100
print(L4)
Tup = ("jay","viru","akii")
print(Tup)
##Tup1 = Tup[1]="dfdf" this is imutable we can not change

## Write a program to demonstrate the use of logical operators
L1 = [1,2,3,4]
L2 = ["ram","shyam","ravind"]
if 2 in L1:
  print(L2[1])
else:
  print("this is not in list")
Price = [100,200,300]
Price2 = [200,300,400]
cust = input("enter custmer catg ")
if cust == "p":
  print(Price)
else:
  print(Price2)

##0 Write a Python program to convert user input from string to integer, float, and boolean types
Cast = int(input("please inter Id: "))
print(f"Your ID is noted {Cast}")
cast2 = float(Cast)
print(f"your id is noted {cast2}")

##0 Write code to demonstrate type casting with list elements
L1 = [2,4,3,8,9]
print(float(L1[2]))

## Write a program that checks if a number is positive, negative, or zero
L1 = [25,2,0,-2]
for i in L1:
  if i >0:
    print(f"{i} is a positive number")
  elif i <0:
      print(f"{i} is a negative number")
  else:
    print(f"{i} is zero")

## Write a for loop to print numbers from 1 to 10
for i in range(1,11):
  print(i,end=" ")

## Write a Python program to find the sum of all even numbers between 1 and 500
sum = 0
for i in range(1,51):
  if i%2==0:
    sum=sum+i
print(sum)

##Write a program to reverse a string using a while loop
rev = "Virender"
rev = rev[:-1]
print(rev)
while len(rev)>0:
  print(rev[-1],end=" ")
  rev = rev[:-1]

##Write a Python program to calculate the factorial of a number provided by the user using a while loop
n = 120
fact = 1
while n>0:
  fact = fact+n
  n = n-1

  if n%fact ==0:
    print(fact)

"""Ans 1 >>>Python is a general-purpose interpreted, interactive, object-oriented, and high-level programming language. It is popular because of rich library and is it understand. Its also multipurpose language.  
Ans – 2>>>> what is an interpreter in Python?
An interpreter in Python is a program that reads and executes Python code. Unlike a compiler, which translates the entire code into machine language before execution, an interpreter translates and executes the code line by line.
•  interactive Mode: You can use the interpreter in an interactive mode, which is great for testing small code snippets and debugging.
•  Script Mode: You can also run Python scripts, which are files containing Python code, using the interpreter.
•  Portability: Python interpreters are available for many operating systems, making Python code highly portable.
Ans ->>>>3
Python Keywords are special reserved words which convey a special meaning to the compiler/interpreter. Each keyword have a special meaning and a specific operation. These keywords can't be used as variable.
Following is the List of Python Keywords:
‘False’, ‘None’, ‘True’, ‘and’, ‘as’, ‘assert’, ‘async’, ‘await’, ‘break’, ‘class’, ‘continue’, ‘def’, ‘del’, ‘elif’, ‘else’, ‘except’, ‘finally’, ‘for’, ‘from’, ‘global’, ‘if’, ‘import’, ‘in’, ‘is’, ‘lambda’, ‘nonlocal’, ‘not’, ‘or’, ‘pass’, ‘raise’, ‘return’, ‘try’, ‘while’, ‘with’, ‘yield’.
Ans >> 4
No we can not use keyword as variable name.
Ans – 5>>.
Mutability is we can update or change once defined. Like List, we can update.
Ans>6
List is mutable and tuples are not due to it has different properties. While programming we need some to keep some elements constant in that case we use Tuples and we want to update or change elements after creation we can use list.
Ans7
There is no difference between “==” and is operator both are comparison operator  
Ans>>8
Logical operators are used to combine conditional statements. (<, >, <=, >=,!, !=,= and, or,XOR)
Ans>>9
Type casting is covert one data type into another data type, there is two type of casting one is implicit and explicit casting.
Implicit casting is done by python automatically.
Explicit casting that’s done by programmer using python inbuilt function like(str, int,float.)
Ans- 10
Implicit casting is done by python automatically.
Explicit casting that’s done by programmer using python inbuilt function like(str, int,float.)
Ans -11
Conditional statements in Python are used to execute different blocks of code based on certain conditions. They allow your program to make decisions and perform different actions depending on whether a condition is true or false. The main types of conditional statements in Python are if elif, else.
Ans -12
The elif statement in Python is short for "else if." It allows you to check multiple conditions in a sequence. When you have more than one condition to test, you can use elif to add additional checks after an initial if statement. If the if condition is false, Python moves on to the elif condition. If the elif condition is true, the corresponding block of code is executed. If none of the if or elif conditions are true, the else block (if present) is executed.
Ans – 13
While loop execute as long as your condition is true, we use for loop when we in advance that many times we want to execute the code, it iterate the block of code in sequence.
Ans -14 –
Imagine you are writing a program that asks a user to enter their password. You want the program to keep asking for the password until the user enters the correct one. In this case, you don't know how many attempts the user will need, so a while loop is more appropriate.  










"""